/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FarmerProfileRouteImport } from './routes/farmer-profile'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PanchayatRouteImport } from './routes/panchayat'
import { Route as PanchayatHeadRouteImport } from './routes/panchayat-head'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/farmer-profile',
  path: '/farmer-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchayatRoute = PanchayatRouteImport.update({
  id: '/panchayat',
  path: '/panchayat',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchayatHeadRoute = PanchayatHeadRouteImport.update({
  id: '/panchayat-head',
  path: '/panchayat-head',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisory': typeof AdvisoryRoute
  '/alerts': typeof AlertsRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/farmer-profile': typeof FarmerProfileRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/panchayat': typeof PanchayatRoute
  '/panchayat-head': typeof PanchayatHeadRoute
  '/weather': typeof WeatherRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisory': typeof AdvisoryRoute
  '/alerts': typeof AlertsRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/farmer-profile': typeof FarmerProfileRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/panchayat': typeof PanchayatRoute
  '/panchayat-head': typeof PanchayatHeadRoute
  '/weather': typeof WeatherRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisory': typeof AdvisoryRoute
  '/alerts': typeof AlertsRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/farmer-profile': typeof FarmerProfileRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/panchayat': typeof PanchayatRoute
  '/panchayat-head': typeof PanchayatHeadRoute
  '/weather': typeof WeatherRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisory'
    | '/alerts'
    | '/compare'
    | '/dashboard'
    | '/farmer-profile'
    | '/history'
    | '/login'
    | '/panchayat'
    | '/panchayat-head'
    | '/weather'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisory'
    | '/alerts'
    | '/compare'
    | '/dashboard'
    | '/farmer-profile'
    | '/history'
    | '/login'
    | '/panchayat'
    | '/panchayat-head'
    | '/weather'
    | '/api/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisory'
    | '/alerts'
    | '/compare'
    | '/dashboard'
    | '/farmer-profile'
    | '/history'
    | '/login'
    | '/panchayat'
    | '/panchayat-head'
    | '/weather'
    | '/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvisoryRoute: typeof AdvisoryRoute
  AlertsRoute: typeof AlertsRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PanchayatRoute: typeof PanchayatRoute
  PanchayatHeadRoute: typeof PanchayatHeadRoute
  WeatherRoute: typeof WeatherRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer-profile': {
      id: '/farmer-profile'
      path: '/farmer-profile'
      fullPath: '/farmer-profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchayat': {
      id: '/panchayat'
      path: '/panchayat'
      fullPath: '/panchayat'
      preLoaderRoute: typeof PanchayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchayat-head': {
      id: '/panchayat-head'
      path: '/panchayat-head'
      fullPath: '/panchayat-head'
      preLoaderRoute: typeof PanchayatHeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvisoryRoute: AdvisoryRoute,
  AlertsRoute: AlertsRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PanchayatRoute: PanchayatRoute,
  PanchayatHeadRoute: PanchayatHeadRoute,
  WeatherRoute: WeatherRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
